aspnet-core/src/PARPlatform.Web.Host/Models/Ui/HomePageModel.cs
using PARPlatform.Sessions.Dto;

namespace PARPlatform.Web.Models.Ui
{
    public class HomePageModel
    {
        public bool IsMultiTenancyEnabled { get; set; }

        public GetCurrentLoginInformationsOutput LoginInformation { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformation.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformation.Tenant == null
                ? "<span class='tenancy-name'>.\\</span>" + userName
                : "<span class='tenancy-name'>" + LoginInformation.Tenant.TenancyName + "\\" + "</span>" + userName;
        }
    }
}

aspnet-core/src/PARPlatform.Web.Host/Models/Ui/LoginModel.cs
using System.ComponentModel.DataAnnotations;
using Abp.Auditing;

namespace PARPlatform.Web.Models.Ui
{
    public class LoginModel
    {
        [Required]
        public string UserNameOrEmailAddress { get; set; }

        [Required]
        [DisableAuditing]
        public string Password { get; set; }

        public bool RememberMe { get; set; }

        public string TenancyName { get; set; }
    }
}

aspnet-core/src/PARPlatform.Web.Host/Controllers/UiController.cs
using System.Threading.Tasks;
using Abp.Auditing;
using Abp.Authorization;
using Abp.Authorization.Users;
using Abp.Configuration.Startup;
using Abp.UI;
using Microsoft.AspNetCore.Mvc;
using PARPlatform.Authorization;
using PARPlatform.Authorization.Accounts;
using PARPlatform.Authorization.Accounts.Dto;
using PARPlatform.Authorization.Users;
using PARPlatform.Identity;
using PARPlatform.MultiTenancy;
using PARPlatform.Web.Models.Ui;
using PARPlatform.Web.Session;

namespace PARPlatform.Web.Controllers
{
    public class UiController : PARPlatformControllerBase
    {
        private readonly IPerRequestSessionCache _sessionCache;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly IAccountAppService _accountAppService;
        private readonly LogInManager _logInManager;
        private readonly SignInManager _signInManager;
        private readonly AbpLoginResultTypeHelper _abpLoginResultTypeHelper;

        public UiController(
            IPerRequestSessionCache sessionCache,
            IMultiTenancyConfig multiTenancyConfig,
            IAccountAppService accountAppService,
            LogInManager logInManager,
            SignInManager signInManager,
            AbpLoginResultTypeHelper abpLoginResultTypeHelper)
        {
            _sessionCache = sessionCache;
            _multiTenancyConfig = multiTenancyConfig;
            _accountAppService = accountAppService;
            _logInManager = logInManager;
            _signInManager = signInManager;
            _abpLoginResultTypeHelper = abpLoginResultTypeHelper;
        }

        [DisableAuditing]
        public async Task<IActionResult> Index()
        {
            var model = new HomePageModel
            {
                LoginInformation = await _sessionCache.GetCurrentLoginInformationsAsync(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled
            };

            if (model.LoginInformation?.User == null)
            {
                return RedirectToAction("Login");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Login(string returnUrl = "")
        {
            if (!string.IsNullOrEmpty(returnUrl))
            {
                ViewBag.ReturnUrl = returnUrl;
            }

            await _signInManager.SignOutAsync();
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl = "")
        {
            if (model.TenancyName != null)
            {
                var isTenantAvailable = await _accountAppService.IsTenantAvailable(new IsTenantAvailableInput
                {
                    TenancyName = model.TenancyName
                });

                switch (isTenantAvailable.State)
                {
                    case TenantAvailabilityState.InActive:
                        throw new UserFriendlyException(L("TenantIsNotActive", model.TenancyName));
                    case TenantAvailabilityState.NotFound:
                        throw new UserFriendlyException(L("ThereIsNoTenantDefinedWithName{0}", model.TenancyName));
                }
            }

            var loginResult = await GetLoginResultAsync(model.UserNameOrEmailAddress, model.Password, model.TenancyName);

            if (loginResult.User.ShouldChangePasswordOnNextLogin)
            {
                throw new UserFriendlyException(L("RequiresPasswordChange"));
            }

            var signInResult = await _signInManager.SignInOrTwoFactorAsync(loginResult, model.RememberMe);

            if (signInResult.RequiresTwoFactor)
            {
                throw new UserFriendlyException(L("RequiresTwoFactorAuth"));
            }

            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Logout()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index");
        }

        private async Task<AbpLoginResult<Tenant, User>> GetLoginResultAsync(string usernameOrEmailAddress, string password, string tenancyName)
        {
            var loginResult = await _logInManager.LoginAsync(usernameOrEmailAddress, password, tenancyName);

            switch (loginResult.Result)
            {
                case AbpLoginResultType.Success:
                    return loginResult;
                default:
                    throw _abpLoginResultTypeHelper.CreateExceptionForFailedLoginAttempt(loginResult.Result, usernameOrEmailAddress, tenancyName);
            }
        }
    }
}

aspnet-core/src/PARPlatform.Web.Host/Views/Ui/Index.cshtml
@using Abp.Web.Security.AntiForgery
@using Microsoft.AspNetCore.Http
@using PARPlatform.Authorization
@using PARPlatform.Web.Common
@model PARPlatform.Web.Models.Ui.HomePageModel
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@{
    AbpAntiForgeryManager.SetCookie(Context, cookieOptions: new CookieOptions()
    {
        SameSite = SameSiteMode.Strict,
        Secure = true
    });
}
<head>
    <title>PARPlatform</title>

    <link href="~/view-resources/Views/Ui/Index.css" rel="stylesheet" asp-append-version="true"/>
</head>
<div class="main-content">
    <div class="user-name">@L("YouAreAlreadyLoggedInWithUser") : @Html.Raw(Model.GetShownLoginName())</div>
    <div>
        <ul class="content-list">
            @if (WebConsts.SwaggerUiEnabled)
            {
                <li><a href="@WebConsts.SwaggerUiEndPoint">Swagger UI</a></li>
            }
            @if (WebConsts.HangfireDashboardEnabled && IsGranted(AppPermissions.Pages_Administration_HangfireDashboard))
            {
                <li><a href="@WebConsts.HangfireDashboardEndPoint">Hangfire</a></li>
            }
            @if (WebConsts.GraphQL.Enabled && WebConsts.GraphQL.PlaygroundEnabled)
            {
                <li><a href="@WebConsts.GraphQL.PlaygroundEndPoint">GraphQL Playground</a></li>
            }
        </ul>
    </div>
    <div class="logout">
        <a href="@Url.Action("Logout", "Ui", new {area = string.Empty})">@L("Logout")</a>
    </div>
</div>

aspnet-core/src/PARPlatform.Web.Host/Views/Ui/Login.cshtml
@using Abp.Web.Security.AntiForgery
@using PARPlatform
@using Abp.Configuration.Startup
@model PARPlatform.Web.Models.Ui.LoginModel
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@inject IMultiTenancyConfig MultiTenancyConfig
@{
    AbpAntiForgeryManager.SetCookie(Context);
}
<head>
    <title>PARPlatform</title>

    <link href="~/view-resources/Views/Ui/Login.css" rel="stylesheet" asp-append-version="true"/>
</head>
<div class="login-form">
    <h1>@L("LogIn")</h1>
    <form method="post">
        <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl"/>
        
        @if (MultiTenancyConfig.IsEnabled)
        {
            <div class="login-form-row">
                <label for="TenancyName">@L("TenancyName")</label>
                <input type="text" id="TenancyName" name="TenancyName" placeholder="@L("TenancyName")">
            </div>
        }
    
        <div class="login-form-row">
            <label for="UsernameOrEmailAddress">@L("UserNameOrEmail")</label>
            <input type="text" id="UsernameOrEmailAddress" name="UserNameOrEmailAddress" placeholder="@L("UserNameOrEmail")">
        </div>
        <div class="login-form-row">
            <label for="password">@L("Password")</label>
            <input type="password" id="password" name="Password" placeholder="@L("Password")">
        </div>
        <div class="login-form-row">
            <label class="checkbox">
                <input type="checkbox" id="rememberMe" name="RememberMe" value="true">
                <span></span>
                @L("RememberMe")
            </label>
        </div>
        <button type="submit" class="login-form-button">@L("LogIn")</button>
    </form>
    <span style="font-size: 0.8em;font-style:italic"> v@(AppVersionHelper.Version) [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]</span>
</div>